### ISSUE TITLE
Muito bom, você quis garantir que o arquivo ia estar em JS ai botou duas vezes

### ISSUE THREAD

**Issue by gustavobonassa** [AndreEGFerreira/Caesar_Codenation#1]
caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js caesar.js.js

**Comment by AndreEGFerreira** [comment]
Obrigado por prestar atenção neste detalhe, de fato em meu computador o arquivo está com o nome normal, não entendi o motivo de aparecer duas vezes o nome da extensão.

Nome já alterado. Issue já resolvida.
